### ISSUE TITLE
Error when reconnecting to server & Attempting to send messages

### ISSUE THREAD

**Issue by blazedd** [nats-io/node-nats#145]
We've encountered a conditional bug where the NATS client will attempt to send messages, despite no longer being connected to the server. In the code it's not checking to see if the socket is still attached or not and casuses an error. The side affect appears to prevent the application from completing a reconnect as well. Once completely restarted it can once again reconnect to the server.

You can see our code usage here: https://github.com/nodecraft/appframe-nats.js

```
[14:34:40] [LOG]: [NATS] Lost connection from server. Reconnecting... at appframe._log (~/node_modules/appframe/appframe.js:882:15)
[14:34:40] [ERROR]: Cannot read property 'resume' of null
TypeError: Cannot read property 'resume' of null
    at Client.processInbound (~/node_modules/nats/lib/nats.js:761:16)
    at Socket.<anonymous> (~/node_modules/nats/lib/nats.js:468:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20) at appframe.debug (~/node_modules/appframe/appframe.js:864:15)
```

**Comment by aricart** [comment]
@blazedd can you attach the version number as written in the nats.js.

**Comment by blazedd** [comment]
@aricart It uses the latest `0.7.18` that's available on NPM.

**Comment by aricart** [comment]
@blazedd Also are you getting called on 'close', 'disconnect' or 'error'.

**Comment by blazedd** [comment]
@aricart We are only seeing `reconnecting` and `error` events.

**Comment by aricart** [comment]
@blazedd Can you give me your connect options.
the only way that the stream is nullified is by closeStream(). 

If we are raising an error, the error argument ill have additional information. It has several properties. Can you print them out. ie:
```
on('error', function(ne) {
 console.log('error name', ne.name);
 console.log('error message', ne.message);
 console.log('error code', ne.code);
 console.log('error chained error', ne.chainedError);
});
```

**Comment by blazedd** [comment]
Connect options:
```
"url": "nats://REDACTED:4222",
"user": "REDACTED",
"password": "REDACTED",
"json": true,
"tls": true,
"maxReconnectAttempts": -1
```

Error:
```
name: 'NatsError',
message: '\'Authorization Timeout\'',
code: 'NATS_PROTOCOL_ERR',
chainedError: undefined
```

**Comment by aricart** [comment]
@blazedd please attach the stack trace where this error is generate

**Comment by blazedd** [comment]
@aricart Fair point. Should have posted that too (whoops)

```
 NatsError: 'Authorization Timeout'
    at Client.processInbound (/home/hub/node_modules/nats/lib/nats.js:788:30)
    at Socket.<anonymous> (/home/hub/node_modules/nats/lib/nats.js:468:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
  name: 'NatsError',
  message: '\'Authorization Timeout\'',
  code: 'NATS_PROTOCOL_ERR',
  chainedError: undefined }
```

ps thanks for being so quick to help! :D

**Comment by aricart** [comment]
I don't want minecraft severs to fail. :)

**Comment by aricart** [comment]
OK we are getting close now. Do you have access to the gnatsd log? There's a timeout on the server authorization. So I would imagine we have a matching error on the server side.

The part that doesn't make sense to me is that if you restart your process it connects fine. Is it possible that you have a cluster and given that 0.7.18 is dynamically updating the client with routes from other servers in the cluster, that one of those servers doesn't have the same authorization setting. One thing to do is. Can you print:

`console.log('servers', nc.servers)`

Where `nc` is your connection.

**Comment by blazedd** [comment]
@aricart Thanks. Our current configuration of NATS is as folllows:

We have a cluster of 3 nodes, 1 in Chicago, another in Phoenix, and a final one in Amsterdam. We have 1 DNS hostname that uses geo-dns to route the connection appropriately, depending where the connection is coming from. Due to this, we're only ever connecting to 1 server explictly via node-nats. Is this not an ideal way to do things?

The nats log at the time, with debug and trace mode enabled is as follows:

```[1] 2017/05/11 15:38:19.958500 [DBG] redacted:36096 - cid:9 - Client connection created
[1] 2017/05/11 15:38:19.958539 [DBG] redacted:36096 - cid:9 - Starting TLS client connection handshake
[1] 2017/05/11 15:38:20.958713 [TRC] redacted:36096 - cid:9 - <<- [-ERR Authorization Timeout]
[1] 2017/05/11 15:38:20.958767 [DBG] redacted:36096 - cid:9 - Authorization Timeout
[1] 2017/05/11 15:38:20.958789 [DBG] redacted:36096 - cid:9 - Client connection closed```

More interestingly our servers:

```
servers [ Server {
    url:
     Url {
       protocol: 'nats:',
       slashes: true,
       auth: null,
       host: 'REDACTED:4222',
       port: '4222',
       hostname: 'REDACTED',
       hash: null,
       search: null,
       query: null,
       pathname: null,
       path: null,
       href: 'nats://REDACTED:4222' },
    didConnect: true,
    reconnects: 0 },
  Server {
    url:
     Url {
       protocol: 'nats:',
       slashes: true,
       auth: null,
       host: '172.17.0.2:4222',
       port: '4222',
       hostname: '172.17.0.2',
       hash: null,
       search: null,
       query: null,
       pathname: null,
       path: null,
       href: 'nats://172.17.0.2:4222' },
    didConnect: false,
    reconnects: 0 } ]
```

After some searching we found that `172.17.0.2` is the local ip assigned by Docker to the clustered node we connected to. Maybe the gnatsd server is telling the client to connect to what it thinks it's IP is (which is technically correct, but not a valid ip). We aren't using the Docker overlay network to connect to these as we're hanging our connection over the web at the current moment.

**Comment by aricart** [comment]
Not sure I am following. But the dockerized nats (https://hub.docker.com/_/nats/) will have clustering setup, and since you seem to be using default ports, if the find each other they will certainly join.

Just to clarify. You are running two gnatsd processes or is the dockerized nats exposed on 2 different IPs?

**Comment by aricart** [comment]
One fix for right now to unblock you is to have the gnatsd use the flag --no_advertise, set up. This will make it so that the client will not get dynamic updates on cluster members.

The other possibility is to change the configuration of the dockerized gnatsd (assuming that their configurations match) to have a config setting that specifies a longer timeout for the authentication:

```
listen: localhost:4242 # host/port to listen for client connections

http: localhost:8222 # HTTP monitoring port

# Authorization for client connections
authorization {
  user:     derek
  # ./util/mkpassword -p T0pS3cr3t
  password: $2a$11$W2zko751KUvVy59mUTWmpOdWjpEm5qhcCZRd05GjI/sSOT.xtiHyG
  timeout:  1
}
```

Also I think the fix/patch for nats.js is simple, but I would like to reproduce the error, and verify it:
```
--- lib/nats.js	(revision 25cddf64124b4be1b581b5bb59e5b7fae19621ba)
+++ lib/nats.js	(revision )
@@ -786,6 +786,8 @@
         // Ignore for now..
       } else if ((m = ERR.exec(buf)) !== null) {
         client.emit('error', new NatsError(m[1], NATS_PROTOCOL_ERR));
+        client.scheduleReconnect();
+        return;
       } else if ((m = PONG.exec(buf)) !== null) {
         var cb = client.pongs && client.pongs.shift();
         if (cb) { cb(); } // FIXME: Should we check for exceptions?
```

**Comment by Cherry** [comment]
Thanks for all your help @aricart!

To clarify our nats setup, we have 3 instances of gnatsd running with Docker, on 3 separate machines (in 3 separate locations). Each one of these instances pass a `--routes` option, referencing the other 2 instances. We then connect to a single DNS hostname (nats.example.com) from all of our applications, which via geo-dns responds with the closest server.

Would it make more sense to connect to all of the servers via `node-nats`, rather than just this single hostname? We did things this way as we have infrastructure communicating from ~5 datacenters across the globe, and wanted to ensure that, for example, all connections in EU only route via our EU gnatsd instance, and not via the US (increased latency is very bad for game servers), but, still provide a fail-over to the US based instances, when issues may be occurring.

Let me know if that makes sense, or if we can clarify anything further.

**Comment by blazedd** [comment]
@aricart Thanks for the `--no_advertise` flag. That certainly _would_ have been an issue at some level. My `nc.server` list now only shows the server we expect, rather than the local network ip. This local network IP is a result of Docker and might be something to consider on the Docker NATS documentation.

That said it still occurs. I also can replicate it with the Node script here: https://gist.github.com/blazedd/fa67e5603450e752f947c140aa69555b

I've also included our nats config and docker commands. We share the config between all clusters via Docker swarm to prevent de-duplicated configs.

**Comment by blazedd** [comment]
After further testing I've also been able to test this with the default docker image running at localhost. This is not a result of clustering. :/

**Comment by ColinSullivan1** [comment]
@blazedd , Regarding the timeout, I think you may be running into CPU contention between password decryption and TLS - you are likely running into [this issue](https://github.com/nats-io/gnatsd/issues/432).  I'd suggest increasing your authorization timeout in the NATS server as @aricart described above in his configuration file example.

**Comment by blazedd** [comment]
New information! This only occurs when TLS is used. I can start/stop and interrupt the connection without any unexpected problems

**Comment by aricart** [comment]
@blazedd @Cherry  the authorization issue is a result of the `timeout:  x` configuration on the docker, and the bug that I posted the patch on.

After your changes to the docker image, how many servers does the nats client know about?

If the answer is 1, one suggestion is that each of the servers should likely a very specific interface or name. This would enable you to actually inspect the server you are connected to. If the nats servers all resolve to the same hostname:port, then the nats client will not add them (since they map to the same) and you won't get visibility into the server you are connecting to.

**Comment by aricart** [comment]
@blazedd  - yes the https://github.com/nats-io/gnatsd/issues/432 contention that @ColinSullivan1 described is what is creating the error on connect. Need to increase the `timeout` setting.

**Comment by blazedd** [comment]
@aricart Not quite the fix we hoped. Regardless what I set the timeout to I get those errors about authorization timeout it always times out until I restart the app. I've tried setting the timeout for each code block (tls, cluster, etc).

**Comment by aricart** [comment]
I'll verify the fix I put the patch for above. This would move you to the next server but unless you change the timeout likely there's not that much we can do until https://github.com/nats-io/gnatsd/issues/432 is resolved.

**Comment by blazedd** [comment]
@aricart The `return` didn't solve the issue for my test. Also in my test I'm not using our cluster in attempt to remove potential variables that we introduced. :)

Thanks again for helping with this!

**Comment by aricart** [comment]
Give me a bit to figure the proper fix.

**Comment by blazedd** [comment]
After a lot of poking around I've found a few problems related to the node-nats client itself.

1. Socket connections are not cleaned up on reconnect or the TLS upgrade.
2. As a result multiple connections are being attempted to gnatsd. Whichever socket last connected gets the data to write to the socket as it's the current reference to the `client.socket` variable.
3. Adding a simple check to see if `client.stream` exists at the top of `client.processInbound` solves the application error originally described in this issue.

I'll keep testing my changes over at blazedd/nats-node

**Comment by aricart** [comment]
The final fix for this issue and other reconnect logic is in https://github.com/nats-io/node-nats/pull/147.

**Comment by Cherry** [comment]
Thanks so much @aricart! Is there an ETA for when this will land in a release?

**Comment by aricart** [comment]
@cherry  it is already in npm!

https://www.npmjs.com/package/nats

**Comment by Cherry** [comment]
Ah, perfect. Thanks @aricart! 😄
